[2023-06-05T08:43:36.740+0000] {processor.py:153} INFO - Started process (PID=809) to work on /opt/airflow/dags/1.py
[2023-06-05T08:43:36.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:43:36.744+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:43:36.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:43:36.763+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:43:36.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:43:36.764+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:43:36.794+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.059 seconds
[2023-06-05T08:44:07.486+0000] {processor.py:153} INFO - Started process (PID=851) to work on /opt/airflow/dags/1.py
[2023-06-05T08:44:07.489+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:44:07.491+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:44:07.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:44:07.503+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:44:07.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:44:07.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:44:07.529+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-05T08:44:38.063+0000] {processor.py:153} INFO - Started process (PID=886) to work on /opt/airflow/dags/1.py
[2023-06-05T08:44:38.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:44:38.074+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:44:38.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:44:38.090+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:44:38.087+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:44:38.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:44:38.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.074 seconds
[2023-06-05T08:45:08.801+0000] {processor.py:153} INFO - Started process (PID=935) to work on /opt/airflow/dags/1.py
[2023-06-05T08:45:08.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:45:08.806+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:45:08.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:45:08.814+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:45:08.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:45:08.816+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:45:08.838+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.041 seconds
[2023-06-05T08:45:39.454+0000] {processor.py:153} INFO - Started process (PID=970) to work on /opt/airflow/dags/1.py
[2023-06-05T08:45:39.457+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:45:39.459+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:45:39.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:45:39.470+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:45:39.467+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:45:39.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:45:39.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-05T08:46:10.083+0000] {processor.py:153} INFO - Started process (PID=1019) to work on /opt/airflow/dags/1.py
[2023-06-05T08:46:10.084+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:46:10.086+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:46:10.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:46:10.093+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:46:10.091+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:46:10.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:46:10.116+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.036 seconds
[2023-06-05T08:46:40.941+0000] {processor.py:153} INFO - Started process (PID=1055) to work on /opt/airflow/dags/1.py
[2023-06-05T08:46:40.944+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:46:40.947+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:46:40.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:46:40.960+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:46:40.956+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:46:40.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:46:40.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.058 seconds
[2023-06-05T08:47:11.710+0000] {processor.py:153} INFO - Started process (PID=1098) to work on /opt/airflow/dags/1.py
[2023-06-05T08:47:11.713+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:47:11.717+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:47:11.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:47:11.735+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:47:11.727+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:47:11.737+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:47:11.768+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.063 seconds
[2023-06-05T08:47:42.501+0000] {processor.py:153} INFO - Started process (PID=1140) to work on /opt/airflow/dags/1.py
[2023-06-05T08:47:42.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:47:42.506+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:47:42.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:47:42.521+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:47:42.514+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:47:42.522+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:47:42.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.060 seconds
[2023-06-05T08:48:13.202+0000] {processor.py:153} INFO - Started process (PID=1175) to work on /opt/airflow/dags/1.py
[2023-06-05T08:48:13.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:48:13.211+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:48:13.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:48:13.231+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:48:13.226+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:48:13.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:48:13.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.083 seconds
[2023-06-05T08:48:44.049+0000] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/1.py
[2023-06-05T08:48:44.052+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:48:44.055+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:48:44.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:48:44.070+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:48:44.065+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:48:44.072+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:48:44.111+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.067 seconds
[2023-06-05T08:49:09.691+0000] {processor.py:153} INFO - Started process (PID=1245) to work on /opt/airflow/dags/1.py
[2023-06-05T08:49:09.694+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:49:09.695+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:49:09.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:49:09.715+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:49:09.712+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:49:09.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:49:09.738+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-05T08:49:40.298+0000] {processor.py:153} INFO - Started process (PID=1294) to work on /opt/airflow/dags/1.py
[2023-06-05T08:49:40.301+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:49:40.302+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:49:40.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:49:40.312+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:49:40.310+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:49:40.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:49:40.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.041 seconds
[2023-06-05T08:50:10.999+0000] {processor.py:153} INFO - Started process (PID=1329) to work on /opt/airflow/dags/1.py
[2023-06-05T08:50:11.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:50:11.003+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:50:11.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:50:11.014+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:50:11.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:50:11.015+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:50:11.038+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-05T08:50:41.645+0000] {processor.py:153} INFO - Started process (PID=1378) to work on /opt/airflow/dags/1.py
[2023-06-05T08:50:41.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:50:41.649+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:50:41.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:50:41.656+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:50:41.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:50:41.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:50:41.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.035 seconds
[2023-06-05T08:51:12.297+0000] {processor.py:153} INFO - Started process (PID=1413) to work on /opt/airflow/dags/1.py
[2023-06-05T08:51:12.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:51:12.302+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:51:12.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:51:12.311+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:51:12.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:51:12.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:51:12.337+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-05T08:51:42.996+0000] {processor.py:153} INFO - Started process (PID=1462) to work on /opt/airflow/dags/1.py
[2023-06-05T08:51:42.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:51:43.000+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:51:43.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:51:43.008+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:51:43.005+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:51:43.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:51:43.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.039 seconds
[2023-06-05T08:52:13.635+0000] {processor.py:153} INFO - Started process (PID=1497) to work on /opt/airflow/dags/1.py
[2023-06-05T08:52:13.637+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:52:13.639+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:52:13.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:52:13.650+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:52:13.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:52:13.651+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:52:13.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-05T08:52:44.304+0000] {processor.py:153} INFO - Started process (PID=1547) to work on /opt/airflow/dags/1.py
[2023-06-05T08:52:44.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:52:44.308+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:52:44.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:52:44.318+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:52:44.315+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:52:44.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:52:44.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-05T08:53:14.989+0000] {processor.py:153} INFO - Started process (PID=1582) to work on /opt/airflow/dags/1.py
[2023-06-05T08:53:14.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T08:53:14.993+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:53:14.993+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T08:53:15.002+0000] {logging_mixin.py:137} INFO - [2023-06-05T08:53:14.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T08:53:15.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T08:53:15.030+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.045 seconds
[2023-06-05T09:03:34.632+0000] {processor.py:153} INFO - Started process (PID=1623) to work on /opt/airflow/dags/1.py
[2023-06-05T09:03:34.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-05T09:03:34.638+0000] {logging_mixin.py:137} INFO - [2023-06-05T09:03:34.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-05T09:03:34.651+0000] {logging_mixin.py:137} INFO - [2023-06-05T09:03:34.645+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-05T09:03:34.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-05T09:03:34.688+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.063 seconds
