[2023-06-06T07:14:45.343+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/1.py
[2023-06-06T07:14:45.345+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:14:45.347+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:14:45.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:14:45.355+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:14:45.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:14:45.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:14:45.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T07:15:16.026+0000] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/1.py
[2023-06-06T07:15:16.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:15:16.031+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:15:16.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:15:16.046+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:15:16.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:15:16.048+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:15:16.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.071 seconds
[2023-06-06T07:15:47.101+0000] {processor.py:153} INFO - Started process (PID=119) to work on /opt/airflow/dags/1.py
[2023-06-06T07:15:47.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:15:47.106+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:15:47.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:15:47.121+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:15:47.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:15:47.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:15:47.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.064 seconds
[2023-06-06T07:16:17.990+0000] {processor.py:153} INFO - Started process (PID=163) to work on /opt/airflow/dags/1.py
[2023-06-06T07:16:17.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:16:17.996+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:16:17.996+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:16:18.011+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:16:18.007+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:16:18.013+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:16:18.046+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.063 seconds
[2023-06-06T07:16:48.922+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/1.py
[2023-06-06T07:16:48.924+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:16:48.925+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:16:48.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:16:48.936+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:16:48.934+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:16:48.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:16:48.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T07:17:19.617+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/1.py
[2023-06-06T07:17:19.620+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:17:19.624+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:17:19.624+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:17:19.635+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:17:19.631+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:17:19.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:17:19.662+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T07:17:50.342+0000] {processor.py:153} INFO - Started process (PID=287) to work on /opt/airflow/dags/1.py
[2023-06-06T07:17:50.345+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:17:50.347+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:17:50.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:17:50.359+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:17:50.356+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:17:50.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:17:50.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.055 seconds
[2023-06-06T07:18:21.323+0000] {processor.py:153} INFO - Started process (PID=322) to work on /opt/airflow/dags/1.py
[2023-06-06T07:18:21.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:18:21.328+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:18:21.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:18:21.338+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:18:21.335+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:18:21.340+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:18:21.369+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.052 seconds
[2023-06-06T07:18:52.088+0000] {processor.py:153} INFO - Started process (PID=371) to work on /opt/airflow/dags/1.py
[2023-06-06T07:18:52.092+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:18:52.095+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:18:52.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:18:52.110+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:18:52.105+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:18:52.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:18:52.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.067 seconds
[2023-06-06T07:19:22.891+0000] {processor.py:153} INFO - Started process (PID=405) to work on /opt/airflow/dags/1.py
[2023-06-06T07:19:22.895+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:19:22.896+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:19:22.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:19:22.909+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:19:22.904+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:19:22.911+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:19:22.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.056 seconds
[2023-06-06T07:19:53.815+0000] {processor.py:153} INFO - Started process (PID=449) to work on /opt/airflow/dags/1.py
[2023-06-06T07:19:53.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:19:53.830+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:19:53.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:19:53.851+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:19:53.843+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:19:53.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:19:53.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.114 seconds
[2023-06-06T07:20:24.729+0000] {processor.py:153} INFO - Started process (PID=489) to work on /opt/airflow/dags/1.py
[2023-06-06T07:20:24.731+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:20:24.732+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:20:24.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:20:24.739+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:20:24.737+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:20:24.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:20:24.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.037 seconds
[2023-06-06T07:20:55.489+0000] {processor.py:153} INFO - Started process (PID=524) to work on /opt/airflow/dags/1.py
[2023-06-06T07:20:55.492+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:20:55.494+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:20:55.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:20:55.505+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:20:55.501+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:20:55.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:20:55.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.053 seconds
[2023-06-06T07:21:26.255+0000] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/1.py
[2023-06-06T07:21:26.257+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:21:26.259+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:21:26.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:21:26.268+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:21:26.265+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:21:26.270+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:21:26.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:21:57.002+0000] {processor.py:153} INFO - Started process (PID=608) to work on /opt/airflow/dags/1.py
[2023-06-06T07:21:57.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:21:57.007+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:21:57.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:21:57.018+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:21:57.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:21:57.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:21:57.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T07:22:27.722+0000] {processor.py:153} INFO - Started process (PID=657) to work on /opt/airflow/dags/1.py
[2023-06-06T07:22:27.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:22:27.728+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:22:27.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:22:27.737+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:22:27.734+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:22:27.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:22:27.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:22:58.443+0000] {processor.py:153} INFO - Started process (PID=692) to work on /opt/airflow/dags/1.py
[2023-06-06T07:22:58.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:22:58.448+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:22:58.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:22:58.457+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:22:58.455+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:22:58.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:22:58.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:23:29.194+0000] {processor.py:153} INFO - Started process (PID=741) to work on /opt/airflow/dags/1.py
[2023-06-06T07:23:29.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:23:29.201+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:23:29.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:23:29.215+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:23:29.210+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:23:29.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:23:29.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.065 seconds
[2023-06-06T07:24:00.049+0000] {processor.py:153} INFO - Started process (PID=776) to work on /opt/airflow/dags/1.py
[2023-06-06T07:24:00.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:24:00.053+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:24:00.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:24:00.064+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:24:00.061+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:24:00.066+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:24:00.092+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:24:30.754+0000] {processor.py:153} INFO - Started process (PID=812) to work on /opt/airflow/dags/1.py
[2023-06-06T07:24:30.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:24:30.760+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:24:30.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:24:30.771+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:24:30.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:24:30.773+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:24:30.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.054 seconds
[2023-06-06T07:25:00.868+0000] {processor.py:153} INFO - Started process (PID=855) to work on /opt/airflow/dags/1.py
[2023-06-06T07:25:00.876+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:25:00.879+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:25:00.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:25:00.889+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:25:00.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:25:00.891+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:25:00.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.059 seconds
[2023-06-06T07:25:31.024+0000] {processor.py:153} INFO - Started process (PID=895) to work on /opt/airflow/dags/1.py
[2023-06-06T07:25:31.027+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:25:31.029+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:25:31.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:25:31.039+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:25:31.036+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:25:31.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:25:31.066+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:26:01.667+0000] {processor.py:153} INFO - Started process (PID=930) to work on /opt/airflow/dags/1.py
[2023-06-06T07:26:01.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:26:01.671+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:26:01.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:26:01.680+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:26:01.677+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:26:01.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:26:01.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T07:26:32.399+0000] {processor.py:153} INFO - Started process (PID=979) to work on /opt/airflow/dags/1.py
[2023-06-06T07:26:32.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:26:32.407+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:26:32.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:26:32.421+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:26:32.417+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:26:32.423+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:26:32.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.062 seconds
[2023-06-06T07:27:03.213+0000] {processor.py:153} INFO - Started process (PID=1014) to work on /opt/airflow/dags/1.py
[2023-06-06T07:27:03.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:27:03.218+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:27:03.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:27:03.228+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:27:03.225+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:27:03.230+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:27:03.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:27:33.969+0000] {processor.py:153} INFO - Started process (PID=1058) to work on /opt/airflow/dags/1.py
[2023-06-06T07:27:33.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:27:33.975+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:27:33.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:27:33.991+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:27:33.986+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:27:33.993+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:27:34.048+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.085 seconds
[2023-06-06T07:28:04.927+0000] {processor.py:153} INFO - Started process (PID=1099) to work on /opt/airflow/dags/1.py
[2023-06-06T07:28:04.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:28:04.932+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:28:04.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:28:04.942+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:28:04.940+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:28:04.944+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:28:04.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T07:28:35.874+0000] {processor.py:153} INFO - Started process (PID=1134) to work on /opt/airflow/dags/1.py
[2023-06-06T07:28:35.876+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:28:35.878+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:28:35.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:28:35.885+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:28:35.883+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:28:35.886+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:28:35.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.035 seconds
[2023-06-06T07:29:06.532+0000] {processor.py:153} INFO - Started process (PID=1184) to work on /opt/airflow/dags/1.py
[2023-06-06T07:29:06.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:29:06.537+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:29:06.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:29:06.548+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:29:06.544+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:29:06.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:29:06.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:29:37.272+0000] {processor.py:153} INFO - Started process (PID=1219) to work on /opt/airflow/dags/1.py
[2023-06-06T07:29:37.274+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:29:37.276+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:29:37.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:29:37.288+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:29:37.284+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:29:37.290+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:29:37.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.054 seconds
[2023-06-06T07:30:08.185+0000] {processor.py:153} INFO - Started process (PID=1269) to work on /opt/airflow/dags/1.py
[2023-06-06T07:30:08.188+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:30:08.190+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:30:08.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:30:08.199+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:30:08.195+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:30:08.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:30:08.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T07:30:38.838+0000] {processor.py:153} INFO - Started process (PID=1304) to work on /opt/airflow/dags/1.py
[2023-06-06T07:30:38.841+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:30:38.844+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:30:38.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:30:38.854+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:30:38.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:30:38.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:30:38.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T07:31:09.601+0000] {processor.py:153} INFO - Started process (PID=1353) to work on /opt/airflow/dags/1.py
[2023-06-06T07:31:09.603+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:31:09.604+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:31:09.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:31:09.612+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:31:09.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:31:09.614+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:31:09.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.038 seconds
[2023-06-06T07:31:40.373+0000] {processor.py:153} INFO - Started process (PID=1388) to work on /opt/airflow/dags/1.py
[2023-06-06T07:31:40.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:31:40.378+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:31:40.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:31:40.387+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:31:40.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:31:40.389+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:31:40.414+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:32:10.999+0000] {processor.py:153} INFO - Started process (PID=1423) to work on /opt/airflow/dags/1.py
[2023-06-06T07:32:11.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:32:11.004+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:32:11.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:32:11.017+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:32:11.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:32:11.019+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:32:11.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T07:32:41.678+0000] {processor.py:153} INFO - Started process (PID=1472) to work on /opt/airflow/dags/1.py
[2023-06-06T07:32:41.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:32:41.683+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:32:41.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:32:41.694+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:32:41.690+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:32:41.695+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:32:41.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T07:33:12.413+0000] {processor.py:153} INFO - Started process (PID=1516) to work on /opt/airflow/dags/1.py
[2023-06-06T07:33:12.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:33:12.416+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:33:12.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:33:12.423+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:33:12.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:33:12.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:33:12.444+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.034 seconds
[2023-06-06T07:33:43.049+0000] {processor.py:153} INFO - Started process (PID=1558) to work on /opt/airflow/dags/1.py
[2023-06-06T07:33:43.053+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:33:43.055+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:33:43.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:33:43.069+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:33:43.064+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:33:43.072+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:33:43.103+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.060 seconds
[2023-06-06T07:34:13.714+0000] {processor.py:153} INFO - Started process (PID=1593) to work on /opt/airflow/dags/1.py
[2023-06-06T07:34:13.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:34:13.719+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:34:13.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:34:13.728+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:34:13.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:34:13.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:34:13.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.045 seconds
[2023-06-06T07:34:44.446+0000] {processor.py:153} INFO - Started process (PID=1642) to work on /opt/airflow/dags/1.py
[2023-06-06T07:34:44.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:34:44.450+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:34:44.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:34:44.458+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:34:44.456+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:34:44.460+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:34:44.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:35:15.142+0000] {processor.py:153} INFO - Started process (PID=1677) to work on /opt/airflow/dags/1.py
[2023-06-06T07:35:15.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:35:15.147+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:35:15.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:35:15.159+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:35:15.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:35:15.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:35:15.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T07:35:45.794+0000] {processor.py:153} INFO - Started process (PID=1726) to work on /opt/airflow/dags/1.py
[2023-06-06T07:35:45.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:35:45.799+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:35:45.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:35:45.806+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:35:45.804+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:35:45.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:35:45.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.038 seconds
[2023-06-06T07:36:16.403+0000] {processor.py:153} INFO - Started process (PID=1761) to work on /opt/airflow/dags/1.py
[2023-06-06T07:36:16.405+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:36:16.407+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:36:16.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:36:16.416+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:36:16.412+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:36:16.417+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:36:16.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:36:47.040+0000] {processor.py:153} INFO - Started process (PID=1810) to work on /opt/airflow/dags/1.py
[2023-06-06T07:36:47.044+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:36:47.046+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:36:47.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:36:47.058+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:36:47.054+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:36:47.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:36:47.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.057 seconds
[2023-06-06T07:37:17.372+0000] {processor.py:153} INFO - Started process (PID=1845) to work on /opt/airflow/dags/1.py
[2023-06-06T07:37:17.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:37:17.377+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:37:17.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:37:17.388+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:37:17.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:37:17.389+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:37:17.416+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:37:48.043+0000] {processor.py:153} INFO - Started process (PID=1894) to work on /opt/airflow/dags/1.py
[2023-06-06T07:37:48.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:37:48.048+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:37:48.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:37:48.058+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:37:48.054+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:37:48.059+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:37:48.084+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:38:18.770+0000] {processor.py:153} INFO - Started process (PID=1929) to work on /opt/airflow/dags/1.py
[2023-06-06T07:38:18.771+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:38:18.773+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:38:18.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:38:18.781+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:38:18.779+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:38:18.782+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:38:18.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.035 seconds
[2023-06-06T07:38:49.542+0000] {processor.py:153} INFO - Started process (PID=1978) to work on /opt/airflow/dags/1.py
[2023-06-06T07:38:49.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:38:49.545+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:38:49.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:38:49.552+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:38:49.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:38:49.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:38:49.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.039 seconds
[2023-06-06T07:39:20.230+0000] {processor.py:153} INFO - Started process (PID=2013) to work on /opt/airflow/dags/1.py
[2023-06-06T07:39:20.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:39:20.235+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:39:20.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:39:20.244+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:39:20.241+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:39:20.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:39:20.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T07:39:51.085+0000] {processor.py:153} INFO - Started process (PID=2063) to work on /opt/airflow/dags/1.py
[2023-06-06T07:39:51.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:39:51.090+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:39:51.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:39:51.099+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:39:51.096+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:39:51.101+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:39:51.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T07:40:21.908+0000] {processor.py:153} INFO - Started process (PID=2099) to work on /opt/airflow/dags/1.py
[2023-06-06T07:40:21.912+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:40:21.914+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:40:21.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:40:21.925+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:40:21.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:40:21.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:40:21.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.054 seconds
[2023-06-06T07:40:52.641+0000] {processor.py:153} INFO - Started process (PID=2149) to work on /opt/airflow/dags/1.py
[2023-06-06T07:40:52.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:40:52.647+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:40:52.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:40:52.673+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:40:52.656+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:40:52.675+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:40:52.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.074 seconds
[2023-06-06T07:41:23.423+0000] {processor.py:153} INFO - Started process (PID=2184) to work on /opt/airflow/dags/1.py
[2023-06-06T07:41:23.425+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:41:23.427+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:41:23.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:41:23.437+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:41:23.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:41:23.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:41:23.464+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:41:54.065+0000] {processor.py:153} INFO - Started process (PID=2233) to work on /opt/airflow/dags/1.py
[2023-06-06T07:41:54.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:41:54.071+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:41:54.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:41:54.084+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:41:54.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:41:54.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:41:54.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.053 seconds
[2023-06-06T07:42:24.866+0000] {processor.py:153} INFO - Started process (PID=2268) to work on /opt/airflow/dags/1.py
[2023-06-06T07:42:24.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:42:24.871+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:42:24.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:42:24.882+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:42:24.879+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:42:24.883+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:42:24.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:42:55.533+0000] {processor.py:153} INFO - Started process (PID=2312) to work on /opt/airflow/dags/1.py
[2023-06-06T07:42:55.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:42:55.536+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:42:55.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:42:55.543+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:42:55.541+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:42:55.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:42:55.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.038 seconds
[2023-06-06T07:43:26.170+0000] {processor.py:153} INFO - Started process (PID=2352) to work on /opt/airflow/dags/1.py
[2023-06-06T07:43:26.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:43:26.178+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:43:26.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:43:26.192+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:43:26.187+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:43:26.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:43:26.227+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.062 seconds
[2023-06-06T07:43:56.867+0000] {processor.py:153} INFO - Started process (PID=2387) to work on /opt/airflow/dags/1.py
[2023-06-06T07:43:56.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:43:56.873+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:43:56.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:43:56.886+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:43:56.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:43:56.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:43:56.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.061 seconds
[2023-06-06T07:44:27.552+0000] {processor.py:153} INFO - Started process (PID=2436) to work on /opt/airflow/dags/1.py
[2023-06-06T07:44:27.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:44:27.556+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:44:27.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:44:27.568+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:44:27.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:44:27.570+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:44:27.602+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.055 seconds
[2023-06-06T07:44:58.325+0000] {processor.py:153} INFO - Started process (PID=2471) to work on /opt/airflow/dags/1.py
[2023-06-06T07:44:58.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:44:58.330+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:44:58.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:44:58.340+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:44:58.337+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:44:58.342+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:44:58.367+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T07:45:28.740+0000] {processor.py:153} INFO - Started process (PID=2520) to work on /opt/airflow/dags/1.py
[2023-06-06T07:45:28.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:45:28.744+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:45:28.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:45:28.754+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:45:28.751+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:45:28.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:45:28.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:45:58.956+0000] {processor.py:153} INFO - Started process (PID=2555) to work on /opt/airflow/dags/1.py
[2023-06-06T07:45:58.960+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:45:58.963+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:45:58.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:45:58.974+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:45:58.970+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:45:58.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:45:59.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.062 seconds
[2023-06-06T07:46:29.898+0000] {processor.py:153} INFO - Started process (PID=2604) to work on /opt/airflow/dags/1.py
[2023-06-06T07:46:29.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:46:29.902+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:46:29.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:46:29.911+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:46:29.908+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:46:29.912+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:46:29.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.038 seconds
[2023-06-06T07:47:00.497+0000] {processor.py:153} INFO - Started process (PID=2639) to work on /opt/airflow/dags/1.py
[2023-06-06T07:47:00.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:47:00.501+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:47:00.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:47:00.507+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:47:00.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:47:00.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:47:00.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.035 seconds
[2023-06-06T07:47:31.065+0000] {processor.py:153} INFO - Started process (PID=2689) to work on /opt/airflow/dags/1.py
[2023-06-06T07:47:31.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:47:31.070+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:47:31.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:47:31.081+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:47:31.077+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:47:31.086+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:47:31.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.054 seconds
[2023-06-06T07:48:01.602+0000] {processor.py:153} INFO - Started process (PID=2724) to work on /opt/airflow/dags/1.py
[2023-06-06T07:48:01.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:48:01.606+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:48:01.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:48:01.614+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:48:01.612+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:48:01.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:48:01.640+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:48:32.060+0000] {processor.py:153} INFO - Started process (PID=2773) to work on /opt/airflow/dags/1.py
[2023-06-06T07:48:32.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:48:32.065+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:48:32.064+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:48:32.072+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:48:32.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:48:32.074+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:48:32.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.041 seconds
[2023-06-06T07:49:02.545+0000] {processor.py:153} INFO - Started process (PID=2808) to work on /opt/airflow/dags/1.py
[2023-06-06T07:49:02.547+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:49:02.548+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:49:02.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:49:02.557+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:49:02.554+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:49:02.558+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:49:02.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:49:33.339+0000] {processor.py:153} INFO - Started process (PID=2845) to work on /opt/airflow/dags/1.py
[2023-06-06T07:49:33.341+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:49:33.343+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:49:33.342+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:49:33.353+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:49:33.350+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:49:33.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:49:33.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T07:50:03.970+0000] {processor.py:153} INFO - Started process (PID=2892) to work on /opt/airflow/dags/1.py
[2023-06-06T07:50:03.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:50:03.974+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:50:03.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:50:03.981+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:50:03.979+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:50:03.982+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:50:04.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.037 seconds
[2023-06-06T07:50:34.580+0000] {processor.py:153} INFO - Started process (PID=2927) to work on /opt/airflow/dags/1.py
[2023-06-06T07:50:34.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:50:34.583+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:50:34.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:50:34.596+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:50:34.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:50:34.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:50:34.622+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:51:05.365+0000] {processor.py:153} INFO - Started process (PID=2977) to work on /opt/airflow/dags/1.py
[2023-06-06T07:51:05.367+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:51:05.369+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:51:05.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:51:05.379+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:51:05.376+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:51:05.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:51:05.408+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.046 seconds
[2023-06-06T07:51:36.079+0000] {processor.py:153} INFO - Started process (PID=3012) to work on /opt/airflow/dags/1.py
[2023-06-06T07:51:36.081+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:51:36.082+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:51:36.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:51:36.092+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:51:36.089+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:51:36.094+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:51:36.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:52:06.826+0000] {processor.py:153} INFO - Started process (PID=3061) to work on /opt/airflow/dags/1.py
[2023-06-06T07:52:06.828+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:52:06.830+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:52:06.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:52:06.839+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:52:06.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:52:06.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:52:06.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T07:52:37.472+0000] {processor.py:153} INFO - Started process (PID=3096) to work on /opt/airflow/dags/1.py
[2023-06-06T07:52:37.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:52:37.476+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:52:37.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:52:37.487+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:52:37.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:52:37.489+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:52:37.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:53:08.037+0000] {processor.py:153} INFO - Started process (PID=3146) to work on /opt/airflow/dags/1.py
[2023-06-06T07:53:08.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:53:08.043+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:53:08.043+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:53:08.055+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:53:08.051+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:53:08.057+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:53:08.090+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.059 seconds
[2023-06-06T07:53:38.552+0000] {processor.py:153} INFO - Started process (PID=3181) to work on /opt/airflow/dags/1.py
[2023-06-06T07:53:38.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:53:38.557+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:53:38.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:53:38.567+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:53:38.563+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:53:38.569+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:53:38.595+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:54:09.215+0000] {processor.py:153} INFO - Started process (PID=3225) to work on /opt/airflow/dags/1.py
[2023-06-06T07:54:09.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:54:09.219+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:54:09.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:54:09.228+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:54:09.225+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:54:09.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:54:09.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T07:54:39.740+0000] {processor.py:153} INFO - Started process (PID=3265) to work on /opt/airflow/dags/1.py
[2023-06-06T07:54:39.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:54:39.746+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:54:39.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:54:39.759+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:54:39.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:54:39.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:54:39.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.056 seconds
[2023-06-06T07:55:10.402+0000] {processor.py:153} INFO - Started process (PID=3300) to work on /opt/airflow/dags/1.py
[2023-06-06T07:55:10.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:55:10.406+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:55:10.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:55:10.418+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:55:10.414+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:55:10.419+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:55:10.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T07:55:41.103+0000] {processor.py:153} INFO - Started process (PID=3350) to work on /opt/airflow/dags/1.py
[2023-06-06T07:55:41.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:55:41.106+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:55:41.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:55:41.115+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:55:41.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:55:41.117+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:55:41.141+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T07:56:11.693+0000] {processor.py:153} INFO - Started process (PID=3385) to work on /opt/airflow/dags/1.py
[2023-06-06T07:56:11.695+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:56:11.697+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:56:11.697+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:56:11.708+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:56:11.704+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:56:11.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:56:11.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T07:56:42.401+0000] {processor.py:153} INFO - Started process (PID=3435) to work on /opt/airflow/dags/1.py
[2023-06-06T07:56:42.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:56:42.405+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:56:42.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:56:42.415+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:56:42.412+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:56:42.416+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:56:42.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.045 seconds
[2023-06-06T07:57:13.077+0000] {processor.py:153} INFO - Started process (PID=3470) to work on /opt/airflow/dags/1.py
[2023-06-06T07:57:13.080+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:57:13.083+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:57:13.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:57:13.093+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:57:13.091+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:57:13.095+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:57:13.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T07:57:43.603+0000] {processor.py:153} INFO - Started process (PID=3519) to work on /opt/airflow/dags/1.py
[2023-06-06T07:57:43.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:57:43.609+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:57:43.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:57:43.618+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:57:43.615+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:57:43.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:57:43.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T07:58:14.271+0000] {processor.py:153} INFO - Started process (PID=3554) to work on /opt/airflow/dags/1.py
[2023-06-06T07:58:14.274+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:58:14.276+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:58:14.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:58:14.285+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:58:14.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:58:14.286+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:58:14.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T07:58:45.020+0000] {processor.py:153} INFO - Started process (PID=3603) to work on /opt/airflow/dags/1.py
[2023-06-06T07:58:45.022+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:58:45.023+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:58:45.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:58:45.032+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:58:45.029+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:58:45.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:58:45.061+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T07:59:15.638+0000] {processor.py:153} INFO - Started process (PID=3638) to work on /opt/airflow/dags/1.py
[2023-06-06T07:59:15.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:59:15.642+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:59:15.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:59:15.650+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:59:15.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:59:15.652+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:59:15.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.039 seconds
[2023-06-06T07:59:46.113+0000] {processor.py:153} INFO - Started process (PID=3687) to work on /opt/airflow/dags/1.py
[2023-06-06T07:59:46.115+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T07:59:46.117+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:59:46.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T07:59:46.127+0000] {logging_mixin.py:137} INFO - [2023-06-06T07:59:46.123+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T07:59:46.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T07:59:46.153+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.045 seconds
[2023-06-06T08:00:16.747+0000] {processor.py:153} INFO - Started process (PID=3722) to work on /opt/airflow/dags/1.py
[2023-06-06T08:00:16.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:00:16.750+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:00:16.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:00:16.759+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:00:16.756+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:00:16.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:00:16.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.037 seconds
[2023-06-06T08:00:47.477+0000] {processor.py:153} INFO - Started process (PID=3771) to work on /opt/airflow/dags/1.py
[2023-06-06T08:00:47.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:00:47.481+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:00:47.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:00:47.489+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:00:47.486+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:00:47.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:00:47.545+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.072 seconds
[2023-06-06T08:01:18.134+0000] {processor.py:153} INFO - Started process (PID=3806) to work on /opt/airflow/dags/1.py
[2023-06-06T08:01:18.135+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:01:18.137+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:01:18.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:01:18.144+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:01:18.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:01:18.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:01:18.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.039 seconds
[2023-06-06T08:01:48.673+0000] {processor.py:153} INFO - Started process (PID=3855) to work on /opt/airflow/dags/1.py
[2023-06-06T08:01:48.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:01:48.677+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:01:48.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:01:48.686+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:01:48.683+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:01:48.687+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:01:48.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T08:02:19.365+0000] {processor.py:153} INFO - Started process (PID=3890) to work on /opt/airflow/dags/1.py
[2023-06-06T08:02:19.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:02:19.370+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:02:19.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:02:19.380+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:02:19.377+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:02:19.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:02:19.408+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T08:02:49.958+0000] {processor.py:153} INFO - Started process (PID=3939) to work on /opt/airflow/dags/1.py
[2023-06-06T08:02:49.959+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:02:49.961+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:02:49.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:02:49.969+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:02:49.967+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:02:49.971+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:02:49.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.041 seconds
[2023-06-06T08:03:20.468+0000] {processor.py:153} INFO - Started process (PID=3974) to work on /opt/airflow/dags/1.py
[2023-06-06T08:03:20.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:03:20.475+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:03:20.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:03:20.491+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:03:20.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:03:20.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:03:20.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.080 seconds
[2023-06-06T08:03:51.222+0000] {processor.py:153} INFO - Started process (PID=4009) to work on /opt/airflow/dags/1.py
[2023-06-06T08:03:51.226+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:03:51.229+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:03:51.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:03:51.241+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:03:51.238+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 10, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:03:51.244+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:03:51.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.064 seconds
[2023-06-06T08:20:18.648+0000] {processor.py:153} INFO - Started process (PID=50) to work on /opt/airflow/dags/1.py
[2023-06-06T08:20:18.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:20:18.652+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:20:18.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:20:18.676+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:20:18.672+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:20:18.678+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:20:18.711+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.067 seconds
[2023-06-06T08:20:49.548+0000] {processor.py:153} INFO - Started process (PID=85) to work on /opt/airflow/dags/1.py
[2023-06-06T08:20:49.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:20:49.551+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:20:49.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:20:49.564+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:20:49.561+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:20:49.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:20:49.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T08:21:20.214+0000] {processor.py:153} INFO - Started process (PID=129) to work on /opt/airflow/dags/1.py
[2023-06-06T08:21:20.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:21:20.221+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:21:20.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:21:20.234+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:21:20.231+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:21:20.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:21:20.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.068 seconds
[2023-06-06T08:21:51.008+0000] {processor.py:153} INFO - Started process (PID=169) to work on /opt/airflow/dags/1.py
[2023-06-06T08:21:51.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:21:51.012+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:21:51.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:21:51.023+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:21:51.020+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:21:51.025+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:21:51.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:22:21.700+0000] {processor.py:153} INFO - Started process (PID=204) to work on /opt/airflow/dags/1.py
[2023-06-06T08:22:21.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:22:21.705+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:22:21.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:22:21.715+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:22:21.712+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:22:21.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:22:21.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T08:22:52.401+0000] {processor.py:153} INFO - Started process (PID=253) to work on /opt/airflow/dags/1.py
[2023-06-06T08:22:52.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:22:52.404+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:22:52.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:22:52.414+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:22:52.411+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:22:52.416+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:22:52.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.045 seconds
[2023-06-06T08:23:23.145+0000] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/1.py
[2023-06-06T08:23:23.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:23:23.150+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:23:23.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:23:23.166+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:23:23.162+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:23:23.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:23:23.206+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.066 seconds
[2023-06-06T08:23:53.901+0000] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/1.py
[2023-06-06T08:23:53.904+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:23:53.906+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:23:53.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:23:53.916+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:23:53.913+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:23:53.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:23:53.944+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:24:24.567+0000] {processor.py:153} INFO - Started process (PID=372) to work on /opt/airflow/dags/1.py
[2023-06-06T08:24:24.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:24:24.571+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:24:24.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:24:24.582+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:24:24.578+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:24:24.583+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:24:24.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T08:24:55.258+0000] {processor.py:153} INFO - Started process (PID=421) to work on /opt/airflow/dags/1.py
[2023-06-06T08:24:55.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:24:55.263+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:24:55.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:24:55.275+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:24:55.270+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:24:55.276+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:24:55.308+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.056 seconds
[2023-06-06T08:25:26.151+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/1.py
[2023-06-06T08:25:26.152+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:25:26.155+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:25:26.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:25:26.166+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:25:26.162+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:25:26.168+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:25:26.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.053 seconds
[2023-06-06T08:25:56.808+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/1.py
[2023-06-06T08:25:56.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:25:56.811+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:25:56.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:25:56.819+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:25:56.817+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:25:56.820+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:25:56.845+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.042 seconds
[2023-06-06T08:26:27.535+0000] {processor.py:153} INFO - Started process (PID=539) to work on /opt/airflow/dags/1.py
[2023-06-06T08:26:27.537+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:26:27.539+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:26:27.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:26:27.549+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:26:27.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:26:27.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:26:27.579+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:26:58.232+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/1.py
[2023-06-06T08:26:58.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:26:58.237+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:26:58.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:26:58.247+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:26:58.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:26:58.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:26:58.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T08:27:28.877+0000] {processor.py:153} INFO - Started process (PID=624) to work on /opt/airflow/dags/1.py
[2023-06-06T08:27:28.880+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:27:28.881+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:27:28.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:27:28.895+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:27:28.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:27:28.896+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:27:28.925+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.054 seconds
[2023-06-06T08:27:59.643+0000] {processor.py:153} INFO - Started process (PID=659) to work on /opt/airflow/dags/1.py
[2023-06-06T08:27:59.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:27:59.648+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:27:59.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:27:59.657+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:27:59.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:27:59.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:27:59.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T08:28:30.328+0000] {processor.py:153} INFO - Started process (PID=708) to work on /opt/airflow/dags/1.py
[2023-06-06T08:28:30.331+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:28:30.333+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:28:30.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:28:30.342+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:28:30.339+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:28:30.344+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:28:30.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.047 seconds
[2023-06-06T08:29:01.006+0000] {processor.py:153} INFO - Started process (PID=744) to work on /opt/airflow/dags/1.py
[2023-06-06T08:29:01.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:29:01.013+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:29:01.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:29:01.035+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:29:01.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:29:01.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:29:01.117+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.118 seconds
[2023-06-06T08:29:31.940+0000] {processor.py:153} INFO - Started process (PID=779) to work on /opt/airflow/dags/1.py
[2023-06-06T08:29:31.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:29:31.945+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:29:31.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:29:31.957+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:29:31.953+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:29:31.958+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:29:31.987+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.052 seconds
[2023-06-06T08:30:02.632+0000] {processor.py:153} INFO - Started process (PID=828) to work on /opt/airflow/dags/1.py
[2023-06-06T08:30:02.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:30:02.637+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:30:02.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:30:02.647+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:30:02.644+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:30:02.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:30:02.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T08:30:33.401+0000] {processor.py:153} INFO - Started process (PID=863) to work on /opt/airflow/dags/1.py
[2023-06-06T08:30:33.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:30:33.405+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:30:33.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:30:33.417+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:30:33.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:30:33.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:30:33.446+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:31:04.086+0000] {processor.py:153} INFO - Started process (PID=913) to work on /opt/airflow/dags/1.py
[2023-06-06T08:31:04.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:31:04.091+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:31:04.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:31:04.106+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:31:04.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:31:04.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:31:04.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.070 seconds
[2023-06-06T08:31:34.863+0000] {processor.py:153} INFO - Started process (PID=948) to work on /opt/airflow/dags/1.py
[2023-06-06T08:31:34.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:31:34.869+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:31:34.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:31:34.879+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:31:34.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:31:34.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:31:34.915+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.057 seconds
[2023-06-06T08:32:05.662+0000] {processor.py:153} INFO - Started process (PID=983) to work on /opt/airflow/dags/1.py
[2023-06-06T08:32:05.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:32:05.666+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:32:05.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:32:05.677+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:32:05.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:32:05.679+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:32:05.709+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.053 seconds
[2023-06-06T08:32:36.386+0000] {processor.py:153} INFO - Started process (PID=1031) to work on /opt/airflow/dags/1.py
[2023-06-06T08:32:36.390+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:32:36.411+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:32:36.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:32:36.424+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:32:36.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:32:36.426+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:32:36.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.077 seconds
[2023-06-06T08:33:07.191+0000] {processor.py:153} INFO - Started process (PID=1066) to work on /opt/airflow/dags/1.py
[2023-06-06T08:33:07.193+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:33:07.195+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:33:07.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:33:07.206+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:33:07.203+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:33:07.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:33:07.235+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:33:38.049+0000] {processor.py:153} INFO - Started process (PID=1115) to work on /opt/airflow/dags/1.py
[2023-06-06T08:33:38.052+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:33:38.054+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:33:38.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:33:38.065+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:33:38.061+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:33:38.068+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:33:38.105+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.063 seconds
[2023-06-06T08:34:08.864+0000] {processor.py:153} INFO - Started process (PID=1150) to work on /opt/airflow/dags/1.py
[2023-06-06T08:34:08.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:34:08.868+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:34:08.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:34:08.876+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:34:08.874+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:34:08.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:34:08.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.043 seconds
[2023-06-06T08:34:39.561+0000] {processor.py:153} INFO - Started process (PID=1194) to work on /opt/airflow/dags/1.py
[2023-06-06T08:34:39.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:34:39.565+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:34:39.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:34:39.573+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:34:39.571+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:34:39.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:34:39.601+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.044 seconds
[2023-06-06T08:35:10.475+0000] {processor.py:153} INFO - Started process (PID=1234) to work on /opt/airflow/dags/1.py
[2023-06-06T08:35:10.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:35:10.480+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:35:10.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:35:10.491+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:35:10.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:35:10.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:35:10.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.052 seconds
[2023-06-06T08:35:41.324+0000] {processor.py:153} INFO - Started process (PID=1278) to work on /opt/airflow/dags/1.py
[2023-06-06T08:35:41.328+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:35:41.330+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:35:41.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:35:41.343+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:35:41.339+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:35:41.346+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:35:41.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.062 seconds
[2023-06-06T08:36:12.113+0000] {processor.py:153} INFO - Started process (PID=1318) to work on /opt/airflow/dags/1.py
[2023-06-06T08:36:12.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:36:12.118+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:36:12.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:36:12.129+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:36:12.125+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:36:12.130+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:36:12.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.049 seconds
[2023-06-06T08:36:42.787+0000] {processor.py:153} INFO - Started process (PID=1353) to work on /opt/airflow/dags/1.py
[2023-06-06T08:36:42.789+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:36:42.791+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:36:42.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:36:42.801+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:36:42.798+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:36:42.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:36:42.833+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.050 seconds
[2023-06-06T08:37:13.606+0000] {processor.py:153} INFO - Started process (PID=1402) to work on /opt/airflow/dags/1.py
[2023-06-06T08:37:13.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:37:13.610+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:37:13.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:37:13.621+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:37:13.617+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:37:13.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:37:13.652+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.051 seconds
[2023-06-06T08:37:44.366+0000] {processor.py:153} INFO - Started process (PID=1437) to work on /opt/airflow/dags/1.py
[2023-06-06T08:37:44.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:37:44.370+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:37:44.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:37:44.380+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:37:44.377+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:37:44.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:37:44.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.048 seconds
[2023-06-06T08:38:15.121+0000] {processor.py:153} INFO - Started process (PID=1486) to work on /opt/airflow/dags/1.py
[2023-06-06T08:38:15.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/1.py for tasks to queue
[2023-06-06T08:38:15.125+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:38:15.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/1.py
[2023-06-06T08:38:15.139+0000] {logging_mixin.py:137} INFO - [2023-06-06T08:38:15.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/1.py", line 13, in <module>
    user_name = os.environ["airflow"]
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'airflow'
[2023-06-06T08:38:15.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/1.py
[2023-06-06T08:38:15.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/1.py took 0.052 seconds
